"use client";

export default function TermsAndCondition() {
  return (
    <>
      <section className="font-serif m-6 md:m-14 md:ml-36 md:mr-36 text-gray-800">
        <div className="text-center text-3xl">
          <h1 className="font-semibold">Terms & Conditions</h1>
          <p className="text-sm mt-2">Updated at 2023-11-06</p>
        </div>

        <div className="mt-10 space-y-8 text-justify">
          {/* General Terms */}
          <div>
            <h2 className="text-2xl font-semibold">General Terms</h2>
            <p className="mt-3">
              By accessing and placing an order with Aadi Finance, you confirm
              that you are in agreement with and bound by the terms of service
              contained in the Terms & Conditions outlined below. These terms
              apply to the entire website and any email or other type of
              communication between you and Aadi Finance.
            </p>

            <p className="mt-3">
              Under no circumstances shall Aadi Finance team be liable for any
              direct, indirect, special, incidental, or consequential damages,
              including, but not limited to, loss of data or profit, arising out
              of the use, or the inability to use, the materials on this site.
            </p>

            <p className="mt-3">
              Aadi Finance will not be responsible for any outcome that may
              occur during the course of usage of our resources. We reserve the
              right to change prices and revise the resources usage policy at
              any moment without prior notice.
            </p>
          </div>

          {/* License */}
          <div>
            <h2 className="text-2xl font-semibold">License</h2>

            <p className="mt-3">
              Aadi Finance grants you a revocable, non-exclusive,
              non-transferable, limited license to download, install and use the
              website strictly in accordance with the terms of this Agreement.
            </p>

            <p className="mt-3">
              These Terms & Conditions are a contract between you and Aadi
              Finance. If you do not agree to these Terms & Conditions, please
              do not use the Aadi Finance Service.
            </p>
          </div>

          {/* Definitions */}
          <div>
            <h2 className="text-2xl font-semibold">
              Definitions and Key Terms
            </h2>

            <div className="space-y-4 mt-4">
              <div>
                <h3 className="font-semibold">Cookie</h3>
                <p>
                  Small amount of data generated by a website and saved by your
                  web browser.
                </p>
              </div>

              <div>
                <h3 className="font-semibold">Company</h3>
                <p>
                  Refers to Aadi Finance, responsible for your information under
                  this Terms & Conditions.
                </p>
              </div>

              <div>
                <h3 className="font-semibold">Country</h3>
                <p>India.</p>
              </div>

              <div>
                <h3 className="font-semibold">Device</h3>
                <p>
                  Any internet-connected device such as a phone, tablet,
                  computer, or any other device used to access the services.
                </p>
              </div>

              <div>
                <h3 className="font-semibold">Service</h3>
                <p>
                  Refers to the services provided by Aadi Finance through the
                  platform.
                </p>
              </div>

              <div>
                <h3 className="font-semibold">Website</h3>
                <p>https://www.webmint.in</p>
              </div>

              <div>
                <h3 className="font-semibold">You</h3>
                <p>
                  A person or entity registered with Aadi Finance to use the
                  Services.
                </p>
              </div>
            </div>
          </div>

          {/* Restrictions */}
          <div>
            <h2 className="text-2xl font-semibold">Restrictions</h2>

            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>
                License, sell, rent, lease, assign, distribute, transmit, host,
                outsource, disclose or otherwise commercially exploit the
                website.
              </li>
              <li>
                Modify, disassemble, decrypt, reverse compile or reverse
                engineer any part of the website.
              </li>
              <li>
                Remove or alter any copyright or trademark notices of Aadi
                Finance.
              </li>
            </ul>
          </div>

          {/* Payment */}
          <div>
            <h2 className="text-2xl font-semibold">Payment</h2>

            <p className="mt-3">
              If you pay for any of our one-time payment plans, you agree to pay
              all fees and charges in accordance with the billing terms in
              effect at the time of payment.
            </p>

            <p className="mt-3">
              By providing payment information, you authorize Aadi Finance to
              verify and charge your payment method for all applicable fees.
            </p>
          </div>

          {/* Cookies */}
          <div>
            <h2 className="text-2xl font-semibold">Cookies</h2>

            <p className="mt-3">
              Aadi Finance uses cookies to identify the areas of our website
              that you have visited and to improve the functionality and
              performance of our services.
            </p>
          </div>

          {/* Third Party Services */}
          <div>
            <h2 className="text-2xl font-semibold">Third-Party Services</h2>

            <p className="mt-3">
              We may display or provide links to third-party services. Aadi
              Finance is not responsible for the content, legality, or accuracy
              of such services.
            </p>
          </div>

          {/* Termination */}
          <div>
            <h2 className="text-2xl font-semibold">Term and Termination</h2>

            <p className="mt-3">
              This Agreement shall remain in effect until terminated by you or
              Aadi Finance. We reserve the right to suspend or terminate access
              without prior notice in case of any violation of these Terms.
            </p>
          </div>

          {/* No Warranties */}
          <div>
            <h2 className="text-2xl font-semibold">No Warranties</h2>

            <p className="mt-3">
              The Website is provided to you “AS IS” and “AS AVAILABLE” without
              warranty of any kind. Aadi Finance disclaims all warranties,
              whether express, implied, statutory, or otherwise.
            </p>
          </div>

          {/* Limitation */}
          <div>
            <h2 className="text-2xl font-semibold">Limitation of Liability</h2>

            <p className="mt-3">
              In no event shall Aadi Finance or its suppliers be liable for any
              indirect, incidental, special, or consequential damages arising
              out of the use of the Website.
            </p>
          </div>

          {/* Intellectual Property */}
          <div>
            <h2 className="text-2xl font-semibold">Intellectual Property</h2>

            <p className="mt-3">
              The Website and its entire contents, including text, images,
              videos, graphics, and software, are owned by Aadi Finance and are
              protected by intellectual property laws.
            </p>
          </div>

          {/* Governing Law */}
          <div>
            <h2 className="text-2xl font-semibold">Choice of Law and Venue</h2>

            <p className="mt-3">
              These Terms shall be governed by the laws of India. Any disputes
              shall be subject to the exclusive jurisdiction of the courts in
              New Delhi, India.
            </p>
          </div>

          {/* Disclaimer */}
          <div>
            <h2 className="text-2xl font-semibold">Disclaimer</h2>

            <p className="mt-3">
              Aadi Finance is not responsible for any content, code, or
              inaccuracies. The Service is provided “as is” without warranties
              or guarantees of any kind.
            </p>
          </div>

          {/* Contact */}
          <div>
            <h2 className="text-2xl font-semibold">Contact Us</h2>

            <p className="mt-3">
              If you have any questions regarding these Terms & Conditions,
              contact us:
            </p>

            <div className="mt-3 space-y-1">
              <p>Email: wecare@dhanly.in</p>
              <p>Phone: 9111249626</p>
            </div>
          </div>

          {/* Privacy Policy */}
          <div>
            <h2 className="text-3xl font-bold mt-16">Privacy Policy</h2>
            <p className="text-sm mt-2">Updated at 2023-11-06</p>

            <p className="mt-4">
              We take security and privacy with the utmost regard. By using this
              Website, you agree to the collection, use, disclosure, and
              dissemination of information in accordance with this Privacy
              Policy.
            </p>

            <div className="space-y-6 mt-6">
              <div>
                <h3 className="font-semibold text-xl">
                  Scope of Privacy Policy
                </h3>

                <p className="mt-2">
                  This Privacy Policy does not apply to third-party services
                  that we do not own or control.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">
                  Information Collection
                </h3>

                <p className="mt-2">
                  We collect information necessary to provide a safe,
                  personalized, and optimized experience to users.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">
                  Sharing of Personal Information
                </h3>

                <p className="mt-2">
                  We may share information with affiliates, service providers,
                  and authorities if required by law.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Your Consent</h3>

                <p className="mt-2">
                  By using the website, you consent to the collection and use of
                  your information in accordance with this Privacy Policy.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Grievance Officer</h3>

                <div className="mt-2 space-y-1">
                  <p>Aadi Finance</p>
                  <p>104, Shalimar, AB Road, Indore</p>
                  <p>Phone: 9111249626</p>
                  <p>Email: wecare@dhanly.in</p>
                  <p>Time: Mon to Fri (9AM to 6PM)</p>
                </div>
              </div>
            </div>
          </div>

          {/* Shipping */}
          <div>
            <h2 className="text-3xl font-bold mt-16">
              Shipping & Payment Policy
            </h2>

            <p className="text-sm mt-2">Updated at 2023-11-06</p>

            <div className="space-y-6 mt-6">
              <div>
                <h3 className="font-semibold text-xl">Delivery Charges</h3>
                <p className="mt-2">
                  All domestic orders are delivered free of charge.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Additional Charges</h3>
                <p className="mt-2">
                  There are no additional charges. Total payable amount is shown
                  on the individual items.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Delivery Time</h3>
                <p className="mt-2">
                  Orders are generally delivered within 4 to 7 business days,
                  excluding public holidays.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Delivery Areas</h3>
                <p className="mt-2">
                  We deliver PAN India. For more details contact:
                </p>

                <div className="mt-2 space-y-1">
                  <p>Phone: 9111249626</p>
                  <p>Email: wecare@dhanly.in</p>
                </div>
              </div>

              <div>
                <h3 className="font-semibold text-xl">Payment Mode</h3>

                <p className="mt-2">
                  Cash on Delivery (COD), Internet Banking, Visa, MasterCard,
                  American Express, Maestro, Debit Cards, and IMPS.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
